# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\main_item_dialog_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ItemDIalog(object):
    def setupUi(self, ItemDIalog):
        ItemDIalog.setObjectName("ItemDIalog")
        ItemDIalog.resize(400, 300)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/window_icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ItemDIalog.setWindowIcon(icon)
        ItemDIalog.setModal(True)
        self.main_layout = QtWidgets.QVBoxLayout(ItemDIalog)
        self.main_layout.setContentsMargins(10, 10, 10, 10)
        self.main_layout.setSpacing(10)
        self.main_layout.setObjectName("main_layout")
        self.lbl_item_id = QtWidgets.QLabel(ItemDIalog)
        self.lbl_item_id.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_item_id.setObjectName("lbl_item_id")
        self.main_layout.addWidget(self.lbl_item_id)
        self.lbl_item_name = QtWidgets.QLabel(ItemDIalog)
        self.lbl_item_name.setObjectName("lbl_item_name")
        self.main_layout.addWidget(self.lbl_item_name)
        self.lnedit_item_name = QtWidgets.QLineEdit(ItemDIalog)
        self.lnedit_item_name.setAlignment(QtCore.Qt.AlignCenter)
        self.lnedit_item_name.setClearButtonEnabled(True)
        self.lnedit_item_name.setObjectName("lnedit_item_name")
        self.main_layout.addWidget(self.lnedit_item_name)
        self.lbl_item_price = QtWidgets.QLabel(ItemDIalog)
        self.lbl_item_price.setObjectName("lbl_item_price")
        self.main_layout.addWidget(self.lbl_item_price)
        self.lnedit_item_price = QtWidgets.QLineEdit(ItemDIalog)
        self.lnedit_item_price.setAlignment(QtCore.Qt.AlignCenter)
        self.lnedit_item_price.setClearButtonEnabled(True)
        self.lnedit_item_price.setObjectName("lnedit_item_price")
        self.main_layout.addWidget(self.lnedit_item_price)
        self.hlo_dialog_buttons = QtWidgets.QHBoxLayout()
        self.hlo_dialog_buttons.setSpacing(10)
        self.hlo_dialog_buttons.setObjectName("hlo_dialog_buttons")
        self.pshbtn_add = QtWidgets.QPushButton(ItemDIalog)
        self.pshbtn_add.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pshbtn_add.setObjectName("pshbtn_add")
        self.hlo_dialog_buttons.addWidget(self.pshbtn_add)
        self.pshbtn_clear = QtWidgets.QPushButton(ItemDIalog)
        self.pshbtn_clear.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pshbtn_clear.setObjectName("pshbtn_clear")
        self.hlo_dialog_buttons.addWidget(self.pshbtn_clear)
        self.pshbtn_cancel = QtWidgets.QPushButton(ItemDIalog)
        self.pshbtn_cancel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pshbtn_cancel.setObjectName("pshbtn_cancel")
        self.hlo_dialog_buttons.addWidget(self.pshbtn_cancel)
        self.hlo_dialog_buttons.setStretch(0, 1)
        self.hlo_dialog_buttons.setStretch(1, 1)
        self.hlo_dialog_buttons.setStretch(2, 1)
        self.main_layout.addLayout(self.hlo_dialog_buttons)
        self.main_layout.setStretch(0, 1)
        self.main_layout.setStretch(1, 1)
        self.main_layout.setStretch(2, 1)
        self.main_layout.setStretch(3, 1)
        self.main_layout.setStretch(4, 1)
        self.main_layout.setStretch(5, 1)

        self.retranslateUi(ItemDIalog)
        QtCore.QMetaObject.connectSlotsByName(ItemDIalog)

    def retranslateUi(self, ItemDIalog):
        _translate = QtCore.QCoreApplication.translate
        ItemDIalog.setWindowTitle(_translate("ItemDIalog", "Chan Pediatric Clinic"))
        self.lbl_item_id.setText(_translate("ItemDIalog", "Item #"))
        self.lbl_item_name.setText(_translate("ItemDIalog", "Name:"))
        self.lnedit_item_name.setPlaceholderText(_translate("ItemDIalog", "Enter name..."))
        self.lbl_item_price.setText(_translate("ItemDIalog", "Price:"))
        self.lnedit_item_price.setPlaceholderText(_translate("ItemDIalog", "Enter price..."))
        self.pshbtn_add.setText(_translate("ItemDIalog", "Add"))
        self.pshbtn_clear.setText(_translate("ItemDIalog", "Clear"))
        self.pshbtn_cancel.setText(_translate("ItemDIalog", "Cancel"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ItemDIalog = QtWidgets.QDialog()
    ui = Ui_ItemDIalog()
    ui.setupUi(ItemDIalog)
    ItemDIalog.show()
    sys.exit(app.exec_())
