# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\main_services_dialog_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ServiceDialog(object):
    def setupUi(self, ServiceDialog):
        ServiceDialog.setObjectName("ServiceDialog")
        ServiceDialog.resize(421, 301)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/window_icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ServiceDialog.setWindowIcon(icon)
        ServiceDialog.setModal(True)
        self.main_layout = QtWidgets.QVBoxLayout(ServiceDialog)
        self.main_layout.setContentsMargins(10, 10, 10, 10)
        self.main_layout.setSpacing(10)
        self.main_layout.setObjectName("main_layout")
        self.lbl_service_id = QtWidgets.QLabel(ServiceDialog)
        self.lbl_service_id.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_service_id.setObjectName("lbl_service_id")
        self.main_layout.addWidget(self.lbl_service_id)
        self.lbl_service_name = QtWidgets.QLabel(ServiceDialog)
        self.lbl_service_name.setObjectName("lbl_service_name")
        self.main_layout.addWidget(self.lbl_service_name)
        self.lnedit_service_name = QtWidgets.QLineEdit(ServiceDialog)
        self.lnedit_service_name.setAlignment(QtCore.Qt.AlignCenter)
        self.lnedit_service_name.setObjectName("lnedit_service_name")
        self.main_layout.addWidget(self.lnedit_service_name)
        self.lbl_price = QtWidgets.QLabel(ServiceDialog)
        self.lbl_price.setObjectName("lbl_price")
        self.main_layout.addWidget(self.lbl_price)
        self.lnedit_price = QtWidgets.QLineEdit(ServiceDialog)
        self.lnedit_price.setAlignment(QtCore.Qt.AlignCenter)
        self.lnedit_price.setObjectName("lnedit_price")
        self.main_layout.addWidget(self.lnedit_price)
        self.hlo_dialog_buttons = QtWidgets.QHBoxLayout()
        self.hlo_dialog_buttons.setSpacing(10)
        self.hlo_dialog_buttons.setObjectName("hlo_dialog_buttons")
        self.pshbtn_add_save = QtWidgets.QPushButton(ServiceDialog)
        self.pshbtn_add_save.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pshbtn_add_save.setObjectName("pshbtn_add_save")
        self.hlo_dialog_buttons.addWidget(self.pshbtn_add_save)
        self.pshbtn_clear_reset = QtWidgets.QPushButton(ServiceDialog)
        self.pshbtn_clear_reset.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pshbtn_clear_reset.setObjectName("pshbtn_clear_reset")
        self.hlo_dialog_buttons.addWidget(self.pshbtn_clear_reset)
        self.pshbtn_cancel = QtWidgets.QPushButton(ServiceDialog)
        self.pshbtn_cancel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pshbtn_cancel.setObjectName("pshbtn_cancel")
        self.hlo_dialog_buttons.addWidget(self.pshbtn_cancel)
        self.hlo_dialog_buttons.setStretch(0, 1)
        self.hlo_dialog_buttons.setStretch(1, 1)
        self.hlo_dialog_buttons.setStretch(2, 1)
        self.main_layout.addLayout(self.hlo_dialog_buttons)

        self.retranslateUi(ServiceDialog)
        QtCore.QMetaObject.connectSlotsByName(ServiceDialog)

    def retranslateUi(self, ServiceDialog):
        _translate = QtCore.QCoreApplication.translate
        ServiceDialog.setWindowTitle(_translate("ServiceDialog", "Chan Pediatric Clinic"))
        self.lbl_service_id.setText(_translate("ServiceDialog", "Service #"))
        self.lbl_service_name.setText(_translate("ServiceDialog", "Name:"))
        self.lnedit_service_name.setPlaceholderText(_translate("ServiceDialog", "Enter name..."))
        self.lbl_price.setText(_translate("ServiceDialog", "Price:"))
        self.lnedit_price.setPlaceholderText(_translate("ServiceDialog", "Enter price..."))
        self.pshbtn_add_save.setText(_translate("ServiceDialog", "Add"))
        self.pshbtn_clear_reset.setText(_translate("ServiceDialog", "Clear"))
        self.pshbtn_cancel.setText(_translate("ServiceDialog", "Cancel"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ServiceDialog = QtWidgets.QDialog()
    ui = Ui_ServiceDialog()
    ui.setupUi(ServiceDialog)
    ServiceDialog.show()
    sys.exit(app.exec_())
