# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\main_consultation_dialog_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConsultationDialog(object):
    def setupUi(self, ConsultationDialog):
        ConsultationDialog.setObjectName("ConsultationDialog")
        ConsultationDialog.resize(400, 400)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/window_icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ConsultationDialog.setWindowIcon(icon)
        self.main_layout = QtWidgets.QVBoxLayout(ConsultationDialog)
        self.main_layout.setContentsMargins(10, 10, 10, 10)
        self.main_layout.setSpacing(10)
        self.main_layout.setObjectName("main_layout")
        self.lbl_consultation_id = QtWidgets.QLabel(ConsultationDialog)
        self.lbl_consultation_id.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_consultation_id.setObjectName("lbl_consultation_id")
        self.main_layout.addWidget(self.lbl_consultation_id)
        self.lbl_patient_name = QtWidgets.QLabel(ConsultationDialog)
        self.lbl_patient_name.setObjectName("lbl_patient_name")
        self.main_layout.addWidget(self.lbl_patient_name)
        self.cmbbx_patient_name = QtWidgets.QComboBox(ConsultationDialog)
        self.cmbbx_patient_name.setEditable(True)
        self.cmbbx_patient_name.setObjectName("cmbbx_patient_name")
        self.main_layout.addWidget(self.cmbbx_patient_name)
        self.lbl_doctor_name = QtWidgets.QLabel(ConsultationDialog)
        self.lbl_doctor_name.setObjectName("lbl_doctor_name")
        self.main_layout.addWidget(self.lbl_doctor_name)
        self.cmbbx_doctor_name = QtWidgets.QComboBox(ConsultationDialog)
        self.cmbbx_doctor_name.setEditable(True)
        self.cmbbx_doctor_name.setObjectName("cmbbx_doctor_name")
        self.main_layout.addWidget(self.cmbbx_doctor_name)
        self.hlo_dialog_buttons = QtWidgets.QHBoxLayout()
        self.hlo_dialog_buttons.setSpacing(10)
        self.hlo_dialog_buttons.setObjectName("hlo_dialog_buttons")
        self.pshbtn_add_save = QtWidgets.QPushButton(ConsultationDialog)
        self.pshbtn_add_save.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pshbtn_add_save.setObjectName("pshbtn_add_save")
        self.hlo_dialog_buttons.addWidget(self.pshbtn_add_save)
        self.pshbtn_clear_reset = QtWidgets.QPushButton(ConsultationDialog)
        self.pshbtn_clear_reset.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pshbtn_clear_reset.setObjectName("pshbtn_clear_reset")
        self.hlo_dialog_buttons.addWidget(self.pshbtn_clear_reset)
        self.pshbtn_cancel = QtWidgets.QPushButton(ConsultationDialog)
        self.pshbtn_cancel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pshbtn_cancel.setObjectName("pshbtn_cancel")
        self.hlo_dialog_buttons.addWidget(self.pshbtn_cancel)
        self.hlo_dialog_buttons.setStretch(0, 1)
        self.hlo_dialog_buttons.setStretch(1, 1)
        self.hlo_dialog_buttons.setStretch(2, 1)
        self.main_layout.addLayout(self.hlo_dialog_buttons)
        self.main_layout.setStretch(0, 1)
        self.main_layout.setStretch(1, 1)
        self.main_layout.setStretch(2, 1)
        self.main_layout.setStretch(3, 1)
        self.main_layout.setStretch(4, 1)

        self.retranslateUi(ConsultationDialog)
        QtCore.QMetaObject.connectSlotsByName(ConsultationDialog)

    def retranslateUi(self, ConsultationDialog):
        _translate = QtCore.QCoreApplication.translate
        ConsultationDialog.setWindowTitle(_translate("ConsultationDialog", "Chan Pediatric Clinic"))
        self.lbl_consultation_id.setText(_translate("ConsultationDialog", "Consultation #"))
        self.lbl_patient_name.setText(_translate("ConsultationDialog", "Patient:"))
        self.lbl_doctor_name.setText(_translate("ConsultationDialog", "Doctor:"))
        self.pshbtn_add_save.setText(_translate("ConsultationDialog", "Save"))
        self.pshbtn_clear_reset.setText(_translate("ConsultationDialog", "Reset"))
        self.pshbtn_cancel.setText(_translate("ConsultationDialog", "Cancel"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ConsultationDialog = QtWidgets.QDialog()
    ui = Ui_ConsultationDialog()
    ui.setupUi(ConsultationDialog)
    ConsultationDialog.show()
    sys.exit(app.exec_())
