# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\main_positions_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Positions(object):
    def setupUi(self, Positions):
        Positions.setObjectName("Positions")
        Positions.resize(997, 811)
        self.main_layout = QtWidgets.QVBoxLayout(Positions)
        self.main_layout.setContentsMargins(10, 10, 10, 10)
        self.main_layout.setSpacing(10)
        self.main_layout.setObjectName("main_layout")
        self.hlo_search_refresh = QtWidgets.QHBoxLayout()
        self.hlo_search_refresh.setSpacing(10)
        self.hlo_search_refresh.setObjectName("hlo_search_refresh")
        self.lbl_search = QtWidgets.QLabel(Positions)
        self.lbl_search.setObjectName("lbl_search")
        self.hlo_search_refresh.addWidget(self.lbl_search)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hlo_search_refresh.addItem(spacerItem)
        self.pshbtn_refresh = QtWidgets.QPushButton(Positions)
        self.pshbtn_refresh.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pshbtn_refresh.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pshbtn_refresh.setIcon(icon)
        self.pshbtn_refresh.setObjectName("pshbtn_refresh")
        self.hlo_search_refresh.addWidget(self.pshbtn_refresh)
        self.hlo_search_refresh.setStretch(1, 1)
        self.main_layout.addLayout(self.hlo_search_refresh)
        self.hlo_archive_search = QtWidgets.QHBoxLayout()
        self.hlo_archive_search.setSpacing(10)
        self.hlo_archive_search.setObjectName("hlo_archive_search")
        self.chkbx_archived = QtWidgets.QCheckBox(Positions)
        self.chkbx_archived.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.chkbx_archived.setObjectName("chkbx_archived")
        self.hlo_archive_search.addWidget(self.chkbx_archived)
        self.lnedit_name = QtWidgets.QLineEdit(Positions)
        self.lnedit_name.setAlignment(QtCore.Qt.AlignCenter)
        self.lnedit_name.setClearButtonEnabled(True)
        self.lnedit_name.setObjectName("lnedit_name")
        self.hlo_archive_search.addWidget(self.lnedit_name)
        self.hlo_archive_search.setStretch(1, 1)
        self.main_layout.addLayout(self.hlo_archive_search)
        self.tblwdgt_positions = QtWidgets.QTableWidget(Positions)
        self.tblwdgt_positions.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tblwdgt_positions.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tblwdgt_positions.setAlternatingRowColors(True)
        self.tblwdgt_positions.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblwdgt_positions.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblwdgt_positions.setCornerButtonEnabled(False)
        self.tblwdgt_positions.setObjectName("tblwdgt_positions")
        self.tblwdgt_positions.setColumnCount(2)
        self.tblwdgt_positions.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblwdgt_positions.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblwdgt_positions.setHorizontalHeaderItem(1, item)
        self.tblwdgt_positions.horizontalHeader().setHighlightSections(False)
        self.tblwdgt_positions.verticalHeader().setVisible(False)
        self.main_layout.addWidget(self.tblwdgt_positions)
        self.hlo_page_buttons = QtWidgets.QHBoxLayout()
        self.hlo_page_buttons.setSpacing(10)
        self.hlo_page_buttons.setObjectName("hlo_page_buttons")
        self.pshbtn_add = QtWidgets.QPushButton(Positions)
        self.pshbtn_add.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pshbtn_add.setObjectName("pshbtn_add")
        self.hlo_page_buttons.addWidget(self.pshbtn_add)
        self.pshbtn_edit = QtWidgets.QPushButton(Positions)
        self.pshbtn_edit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pshbtn_edit.setObjectName("pshbtn_edit")
        self.hlo_page_buttons.addWidget(self.pshbtn_edit)
        self.pshbtn_archive = QtWidgets.QPushButton(Positions)
        self.pshbtn_archive.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pshbtn_archive.setObjectName("pshbtn_archive")
        self.hlo_page_buttons.addWidget(self.pshbtn_archive)
        self.hlo_page_buttons.setStretch(0, 1)
        self.hlo_page_buttons.setStretch(1, 1)
        self.hlo_page_buttons.setStretch(2, 1)
        self.main_layout.addLayout(self.hlo_page_buttons)
        self.main_layout.setStretch(0, 1)
        self.main_layout.setStretch(1, 1)
        self.main_layout.setStretch(2, 17)
        self.main_layout.setStretch(3, 1)

        self.retranslateUi(Positions)
        QtCore.QMetaObject.connectSlotsByName(Positions)

    def retranslateUi(self, Positions):
        _translate = QtCore.QCoreApplication.translate
        Positions.setWindowTitle(_translate("Positions", "Form"))
        self.lbl_search.setText(_translate("Positions", "Search:"))
        self.chkbx_archived.setText(_translate("Positions", "Archived"))
        self.lnedit_name.setPlaceholderText(_translate("Positions", "Enter name..."))
        item = self.tblwdgt_positions.horizontalHeaderItem(0)
        item.setText(_translate("Positions", "ID"))
        item = self.tblwdgt_positions.horizontalHeaderItem(1)
        item.setText(_translate("Positions", "Name"))
        self.pshbtn_add.setText(_translate("Positions", "Add"))
        self.pshbtn_edit.setText(_translate("Positions", "Edit"))
        self.pshbtn_archive.setText(_translate("Positions", "Archive"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Positions = QtWidgets.QWidget()
    ui = Ui_Positions()
    ui.setupUi(Positions)
    Positions.show()
    sys.exit(app.exec_())
