# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\main_sale_change_dialog_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChangeDialog(object):
    def setupUi(self, ChangeDialog):
        ChangeDialog.setObjectName("ChangeDialog")
        ChangeDialog.resize(400, 300)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/window_icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ChangeDialog.setWindowIcon(icon)
        ChangeDialog.setModal(True)
        self.main_layout = QtWidgets.QVBoxLayout(ChangeDialog)
        self.main_layout.setContentsMargins(10, 10, 10, 10)
        self.main_layout.setSpacing(10)
        self.main_layout.setObjectName("main_layout")
        self.lbl_change = QtWidgets.QLabel(ChangeDialog)
        self.lbl_change.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_change.setObjectName("lbl_change")
        self.main_layout.addWidget(self.lbl_change)
        self.lnedit_change = QtWidgets.QLineEdit(ChangeDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnedit_change.sizePolicy().hasHeightForWidth())
        self.lnedit_change.setSizePolicy(sizePolicy)
        self.lnedit_change.setAlignment(QtCore.Qt.AlignCenter)
        self.lnedit_change.setReadOnly(True)
        self.lnedit_change.setObjectName("lnedit_change")
        self.main_layout.addWidget(self.lnedit_change)
        self.pshbtn_ok = QtWidgets.QPushButton(ChangeDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pshbtn_ok.sizePolicy().hasHeightForWidth())
        self.pshbtn_ok.setSizePolicy(sizePolicy)
        self.pshbtn_ok.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pshbtn_ok.setObjectName("pshbtn_ok")
        self.main_layout.addWidget(self.pshbtn_ok)
        self.main_layout.setStretch(0, 1)
        self.main_layout.setStretch(1, 2)
        self.main_layout.setStretch(2, 1)

        self.retranslateUi(ChangeDialog)
        QtCore.QMetaObject.connectSlotsByName(ChangeDialog)
        ChangeDialog.setTabOrder(self.pshbtn_ok, self.lnedit_change)

    def retranslateUi(self, ChangeDialog):
        _translate = QtCore.QCoreApplication.translate
        ChangeDialog.setWindowTitle(_translate("ChangeDialog", "Chan Pediatric Clinic"))
        self.lbl_change.setText(_translate("ChangeDialog", "Change:"))
        self.pshbtn_ok.setText(_translate("ChangeDialog", "OK"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ChangeDialog = QtWidgets.QDialog()
    ui = Ui_ChangeDialog()
    ui.setupUi(ChangeDialog)
    ChangeDialog.show()
    sys.exit(app.exec_())
