# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\main_payment_methods_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PaymentMethods(object):
    def setupUi(self, PaymentMethods):
        PaymentMethods.setObjectName("PaymentMethods")
        PaymentMethods.resize(997, 759)
        self.main_layout = QtWidgets.QVBoxLayout(PaymentMethods)
        self.main_layout.setContentsMargins(10, 10, 10, 10)
        self.main_layout.setSpacing(10)
        self.main_layout.setObjectName("main_layout")
        self.hlo_refresh = QtWidgets.QHBoxLayout()
        self.hlo_refresh.setSpacing(10)
        self.hlo_refresh.setObjectName("hlo_refresh")
        self.lbl_search = QtWidgets.QLabel(PaymentMethods)
        self.lbl_search.setObjectName("lbl_search")
        self.hlo_refresh.addWidget(self.lbl_search)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hlo_refresh.addItem(spacerItem)
        self.pshbtn_refresh = QtWidgets.QPushButton(PaymentMethods)
        self.pshbtn_refresh.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pshbtn_refresh.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pshbtn_refresh.setIcon(icon)
        self.pshbtn_refresh.setObjectName("pshbtn_refresh")
        self.hlo_refresh.addWidget(self.pshbtn_refresh)
        self.main_layout.addLayout(self.hlo_refresh)
        self.hlo_search = QtWidgets.QHBoxLayout()
        self.hlo_search.setSpacing(10)
        self.hlo_search.setObjectName("hlo_search")
        self.chkbx_archived = QtWidgets.QCheckBox(PaymentMethods)
        self.chkbx_archived.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.chkbx_archived.setObjectName("chkbx_archived")
        self.hlo_search.addWidget(self.chkbx_archived)
        self.lnedit_payment_method_name = QtWidgets.QLineEdit(PaymentMethods)
        self.lnedit_payment_method_name.setAlignment(QtCore.Qt.AlignCenter)
        self.lnedit_payment_method_name.setObjectName("lnedit_payment_method_name")
        self.hlo_search.addWidget(self.lnedit_payment_method_name)
        self.main_layout.addLayout(self.hlo_search)
        self.tblwdgt_payment_methods = QtWidgets.QTableWidget(PaymentMethods)
        self.tblwdgt_payment_methods.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tblwdgt_payment_methods.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tblwdgt_payment_methods.setAlternatingRowColors(True)
        self.tblwdgt_payment_methods.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblwdgt_payment_methods.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblwdgt_payment_methods.setCornerButtonEnabled(False)
        self.tblwdgt_payment_methods.setObjectName("tblwdgt_payment_methods")
        self.tblwdgt_payment_methods.setColumnCount(2)
        self.tblwdgt_payment_methods.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblwdgt_payment_methods.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblwdgt_payment_methods.setHorizontalHeaderItem(1, item)
        self.tblwdgt_payment_methods.horizontalHeader().setHighlightSections(False)
        self.tblwdgt_payment_methods.verticalHeader().setVisible(False)
        self.main_layout.addWidget(self.tblwdgt_payment_methods)
        self.hlo_page_buttons = QtWidgets.QHBoxLayout()
        self.hlo_page_buttons.setSpacing(10)
        self.hlo_page_buttons.setObjectName("hlo_page_buttons")
        self.pshbtn_add = QtWidgets.QPushButton(PaymentMethods)
        self.pshbtn_add.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pshbtn_add.setObjectName("pshbtn_add")
        self.hlo_page_buttons.addWidget(self.pshbtn_add)
        self.pshbtn_edit = QtWidgets.QPushButton(PaymentMethods)
        self.pshbtn_edit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pshbtn_edit.setObjectName("pshbtn_edit")
        self.hlo_page_buttons.addWidget(self.pshbtn_edit)
        self.pshbtn_archive = QtWidgets.QPushButton(PaymentMethods)
        self.pshbtn_archive.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pshbtn_archive.setObjectName("pshbtn_archive")
        self.hlo_page_buttons.addWidget(self.pshbtn_archive)
        self.main_layout.addLayout(self.hlo_page_buttons)
        self.main_layout.setStretch(2, 1)

        self.retranslateUi(PaymentMethods)
        QtCore.QMetaObject.connectSlotsByName(PaymentMethods)

    def retranslateUi(self, PaymentMethods):
        _translate = QtCore.QCoreApplication.translate
        PaymentMethods.setWindowTitle(_translate("PaymentMethods", "Form"))
        self.lbl_search.setText(_translate("PaymentMethods", "Search:"))
        self.chkbx_archived.setText(_translate("PaymentMethods", "Archived"))
        self.lnedit_payment_method_name.setPlaceholderText(_translate("PaymentMethods", "Enter name..."))
        item = self.tblwdgt_payment_methods.horizontalHeaderItem(0)
        item.setText(_translate("PaymentMethods", "ID"))
        item = self.tblwdgt_payment_methods.horizontalHeaderItem(1)
        item.setText(_translate("PaymentMethods", "Name"))
        self.pshbtn_add.setText(_translate("PaymentMethods", "Add"))
        self.pshbtn_edit.setText(_translate("PaymentMethods", "Edit"))
        self.pshbtn_archive.setText(_translate("PaymentMethods", "Archive"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PaymentMethods = QtWidgets.QWidget()
    ui = Ui_PaymentMethods()
    ui.setupUi(PaymentMethods)
    PaymentMethods.show()
    sys.exit(app.exec_())
