# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\main_services_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Services(object):
    def setupUi(self, Services):
        Services.setObjectName("Services")
        Services.resize(997, 759)
        self.main_layout = QtWidgets.QVBoxLayout(Services)
        self.main_layout.setContentsMargins(10, 10, 10, 10)
        self.main_layout.setSpacing(10)
        self.main_layout.setObjectName("main_layout")
        self.hlo_refresh = QtWidgets.QHBoxLayout()
        self.hlo_refresh.setSpacing(10)
        self.hlo_refresh.setObjectName("hlo_refresh")
        self.lbl_search = QtWidgets.QLabel(Services)
        self.lbl_search.setObjectName("lbl_search")
        self.hlo_refresh.addWidget(self.lbl_search)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hlo_refresh.addItem(spacerItem)
        self.pshbtn_refresh = QtWidgets.QPushButton(Services)
        self.pshbtn_refresh.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pshbtn_refresh.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pshbtn_refresh.setIcon(icon)
        self.pshbtn_refresh.setObjectName("pshbtn_refresh")
        self.hlo_refresh.addWidget(self.pshbtn_refresh)
        self.main_layout.addLayout(self.hlo_refresh)
        self.hlo_search = QtWidgets.QHBoxLayout()
        self.hlo_search.setSpacing(10)
        self.hlo_search.setObjectName("hlo_search")
        self.chkbx_archived = QtWidgets.QCheckBox(Services)
        self.chkbx_archived.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.chkbx_archived.setObjectName("chkbx_archived")
        self.hlo_search.addWidget(self.chkbx_archived)
        self.lnedit_name = QtWidgets.QLineEdit(Services)
        self.lnedit_name.setAlignment(QtCore.Qt.AlignCenter)
        self.lnedit_name.setObjectName("lnedit_name")
        self.hlo_search.addWidget(self.lnedit_name)
        self.main_layout.addLayout(self.hlo_search)
        self.tblwdgt_services = QtWidgets.QTableWidget(Services)
        self.tblwdgt_services.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tblwdgt_services.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tblwdgt_services.setAlternatingRowColors(True)
        self.tblwdgt_services.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblwdgt_services.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblwdgt_services.setCornerButtonEnabled(False)
        self.tblwdgt_services.setObjectName("tblwdgt_services")
        self.tblwdgt_services.setColumnCount(3)
        self.tblwdgt_services.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblwdgt_services.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblwdgt_services.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblwdgt_services.setHorizontalHeaderItem(2, item)
        self.tblwdgt_services.horizontalHeader().setHighlightSections(False)
        self.tblwdgt_services.verticalHeader().setVisible(False)
        self.main_layout.addWidget(self.tblwdgt_services)
        self.hlo_page_buttons = QtWidgets.QHBoxLayout()
        self.hlo_page_buttons.setSpacing(10)
        self.hlo_page_buttons.setObjectName("hlo_page_buttons")
        self.pshbtn_add = QtWidgets.QPushButton(Services)
        self.pshbtn_add.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pshbtn_add.setObjectName("pshbtn_add")
        self.hlo_page_buttons.addWidget(self.pshbtn_add)
        self.pshbtn_edit = QtWidgets.QPushButton(Services)
        self.pshbtn_edit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pshbtn_edit.setObjectName("pshbtn_edit")
        self.hlo_page_buttons.addWidget(self.pshbtn_edit)
        self.pshbtn_archive = QtWidgets.QPushButton(Services)
        self.pshbtn_archive.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pshbtn_archive.setObjectName("pshbtn_archive")
        self.hlo_page_buttons.addWidget(self.pshbtn_archive)
        self.main_layout.addLayout(self.hlo_page_buttons)
        self.main_layout.setStretch(2, 1)

        self.retranslateUi(Services)
        QtCore.QMetaObject.connectSlotsByName(Services)

    def retranslateUi(self, Services):
        _translate = QtCore.QCoreApplication.translate
        Services.setWindowTitle(_translate("Services", "Form"))
        self.lbl_search.setText(_translate("Services", "Search:"))
        self.chkbx_archived.setText(_translate("Services", "Archived"))
        self.lnedit_name.setPlaceholderText(_translate("Services", "Enter name..."))
        item = self.tblwdgt_services.horizontalHeaderItem(0)
        item.setText(_translate("Services", "ID"))
        item = self.tblwdgt_services.horizontalHeaderItem(1)
        item.setText(_translate("Services", "Name"))
        item = self.tblwdgt_services.horizontalHeaderItem(2)
        item.setText(_translate("Services", "Price"))
        self.pshbtn_add.setText(_translate("Services", "Add"))
        self.pshbtn_edit.setText(_translate("Services", "Edit"))
        self.pshbtn_archive.setText(_translate("Services", "Archive"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Services = QtWidgets.QWidget()
    ui = Ui_Services()
    ui.setupUi(Services)
    Services.show()
    sys.exit(app.exec_())
