# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1350, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1350, 720))
        MainWindow.setMaximumSize(QtCore.QSize(1350, 720))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        MainWindow.setFont(font)
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/window_icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(48, 48))
        self.wdgt_central = QtWidgets.QWidget(MainWindow)
        self.wdgt_central.setObjectName("wdgt_central")
        self.wdgt_central_layout = QtWidgets.QVBoxLayout(self.wdgt_central)
        self.wdgt_central_layout.setContentsMargins(0, 0, 0, 0)
        self.wdgt_central_layout.setSpacing(0)
        self.wdgt_central_layout.setObjectName("wdgt_central_layout")
        self.stckdwdgt_main = QtWidgets.QStackedWidget(self.wdgt_central)
        self.stckdwdgt_main.setObjectName("stckdwdgt_main")
        self.wdgt_central_layout.addWidget(self.stckdwdgt_main)
        MainWindow.setCentralWidget(self.wdgt_central)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Chan Pediatric Clinic"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
