# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\main_payment_method_dialog_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PaymentMethodDialog(object):
    def setupUi(self, PaymentMethodDialog):
        PaymentMethodDialog.setObjectName("PaymentMethodDialog")
        PaymentMethodDialog.resize(421, 301)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/window_icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        PaymentMethodDialog.setWindowIcon(icon)
        PaymentMethodDialog.setModal(True)
        self.main_layout = QtWidgets.QVBoxLayout(PaymentMethodDialog)
        self.main_layout.setContentsMargins(10, 10, 10, 10)
        self.main_layout.setSpacing(10)
        self.main_layout.setObjectName("main_layout")
        self.lbl_payment_method_id = QtWidgets.QLabel(PaymentMethodDialog)
        self.lbl_payment_method_id.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_payment_method_id.setObjectName("lbl_payment_method_id")
        self.main_layout.addWidget(self.lbl_payment_method_id)
        self.lbl_payment_method_name = QtWidgets.QLabel(PaymentMethodDialog)
        self.lbl_payment_method_name.setObjectName("lbl_payment_method_name")
        self.main_layout.addWidget(self.lbl_payment_method_name)
        self.lnedit_payment_method_name = QtWidgets.QLineEdit(PaymentMethodDialog)
        self.lnedit_payment_method_name.setAlignment(QtCore.Qt.AlignCenter)
        self.lnedit_payment_method_name.setObjectName("lnedit_payment_method_name")
        self.main_layout.addWidget(self.lnedit_payment_method_name)
        self.hlo_dialog_buttons = QtWidgets.QHBoxLayout()
        self.hlo_dialog_buttons.setSpacing(10)
        self.hlo_dialog_buttons.setObjectName("hlo_dialog_buttons")
        self.pshbtn_add_save = QtWidgets.QPushButton(PaymentMethodDialog)
        self.pshbtn_add_save.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pshbtn_add_save.setObjectName("pshbtn_add_save")
        self.hlo_dialog_buttons.addWidget(self.pshbtn_add_save)
        self.pshbtn_clear_reset = QtWidgets.QPushButton(PaymentMethodDialog)
        self.pshbtn_clear_reset.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pshbtn_clear_reset.setObjectName("pshbtn_clear_reset")
        self.hlo_dialog_buttons.addWidget(self.pshbtn_clear_reset)
        self.pshbtn_cancel = QtWidgets.QPushButton(PaymentMethodDialog)
        self.pshbtn_cancel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pshbtn_cancel.setObjectName("pshbtn_cancel")
        self.hlo_dialog_buttons.addWidget(self.pshbtn_cancel)
        self.hlo_dialog_buttons.setStretch(0, 1)
        self.hlo_dialog_buttons.setStretch(1, 1)
        self.hlo_dialog_buttons.setStretch(2, 1)
        self.main_layout.addLayout(self.hlo_dialog_buttons)

        self.retranslateUi(PaymentMethodDialog)
        QtCore.QMetaObject.connectSlotsByName(PaymentMethodDialog)

    def retranslateUi(self, PaymentMethodDialog):
        _translate = QtCore.QCoreApplication.translate
        PaymentMethodDialog.setWindowTitle(_translate("PaymentMethodDialog", "Chan Pediatric Clinic"))
        self.lbl_payment_method_id.setText(_translate("PaymentMethodDialog", "Payment Method #"))
        self.lbl_payment_method_name.setText(_translate("PaymentMethodDialog", "Name:"))
        self.lnedit_payment_method_name.setPlaceholderText(_translate("PaymentMethodDialog", "Enter name..."))
        self.pshbtn_add_save.setText(_translate("PaymentMethodDialog", "Add"))
        self.pshbtn_clear_reset.setText(_translate("PaymentMethodDialog", "Clear"))
        self.pshbtn_cancel.setText(_translate("PaymentMethodDialog", "Cancel"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PaymentMethodDialog = QtWidgets.QDialog()
    ui = Ui_PaymentMethodDialog()
    ui.setupUi(PaymentMethodDialog)
    PaymentMethodDialog.show()
    sys.exit(app.exec_())
